{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pcse\n",
    "import yaml\n",
    "import h5py\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "import datetime as dt\n",
    "from multiprocessing import Pool\n",
    "from tqdm.notebook import tqdm, trange\n",
    "import matplotlib.pyplot as plt\n",
    "from pcse.models import Wofost71_PP, Wofost71_WLP_FD\n",
    "from pcse.base import ParameterProvider\n",
    "from pcse.db import NASAPowerWeatherDataProvider\n",
    "from pcse import fileinput as fi\n",
    "from pcse.util import WOFOST71SiteDataProvider"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "agro_yaml = \"\"\"\n",
    "Version: 1.0\n",
    "AgroManagement:\n",
    "- {sim_start_date}:\n",
    "    CropCalendar:\n",
    "        crop_name: maize\n",
    "        variety_name: Maize_VanHeemst_1988\n",
    "        crop_start_type: sowing\n",
    "        crop_start_date: {crop_start_date}\n",
    "        crop_end_type: earliest\n",
    "        crop_end_date: {crop_end_date}\n",
    "        max_duration: 300\n",
    "    TimedEvents: \n",
    "    -   event_signal: apply_n\n",
    "        name:  Nitrogen application table\n",
    "        comment: All nitrogen amounts in g N m-2\n",
    "        events_table:\n",
    "        - {fert_date}: {{amount: {n_rate}, recovery: 0.7}}\n",
    "    StateEvents: null\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "pts = gpd.read_file('../../CIAT/data/BEM_2019_Chiapas_Final_Clean.gpkg')\n",
    "pts['SIM'] = ['CH{0:05d}'.format(i + 1) for i in range(len(pts))]\n",
    "pts = pts.set_index('SIM')\n",
    "pts['lon'] = pts.centroid.x\n",
    "pts['lat'] = pts.centroid.y\n",
    "pts['ref_date'] = pd.to_datetime(pts.fecha_de_siembra)\n",
    "pts['nrate'] = pts.nitrogen/10\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "soildata = {'SMFCF': 0.2, 'SMW': 0.1, 'CRAIRC': 0.1, 'KSUB': 20.0,\n",
    "            'RDMSOL': 200.0, 'K0': 100.0, 'SOPE': 10.0, 'SM0': 0.4}\n",
    "\n",
    "cropdata = fi.YAMLCropDataProvider()\n",
    "cropdata.set_active_crop('maize', 'Maize_VanHeemst_1988')\n",
    "\n",
    "sitedata = WOFOST71SiteDataProvider(WAV=100, CO2=360)\n",
    "\n",
    "parameters = ParameterProvider(cropdata=cropdata, soildata=soildata, sitedata=sitedata)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run(site):\n",
    "        wfile = f'/home/rodrigo7/Apsim_test/MASAGRO/PCSE/{site}_adv010.csv'\n",
    "        wdp = fi.CSVWeatherDataProvider(wfile)\n",
    "\n",
    "        # get new start date\n",
    "        crop_start_date = pts.ref_date.dt.date.loc[site]\n",
    "        sim_start_date = crop_start_date - dt.timedelta(days = 90)\n",
    "        crop_end_date = crop_start_date + dt.timedelta(days = 210)\n",
    "        fert_date = crop_start_date + dt.timedelta(days = 30)\n",
    "        n_rate = 1\n",
    "\n",
    "        # update agromanagement with new start date and load it with yaml.load\n",
    "        tmp = agro_yaml.format(sim_start_date = sim_start_date,\n",
    "                               crop_start_date = crop_start_date,\n",
    "                               crop_end_date = crop_end_date,\n",
    "                               fert_date = fert_date,\n",
    "                               n_rate = n_rate)\n",
    "        agromanagement = yaml.load(tmp, yaml.FullLoader)\n",
    "\n",
    "        wofsim = Wofost71_WLP_FD(parameters, wdp, agromanagement)\n",
    "        wofsim.run_till_terminate()\n",
    "        output = wofsim.get_output()\n",
    "        df = pd.DataFrame(output).set_index(\"day\")\n",
    "        df['SIM'] = site\n",
    "        return(df)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# site = (sites[0])\n",
    "# for site in tqdm(pts.index):\n",
    "#     wfile = f'/home/rodrigo7/Apsim_test/MASAGRO/PCSE/{site}_adv000.csv'\n",
    "#     w = pd.read_csv(wfile, skiprows = 13)\n",
    "#     w.VAP = np.clip(w.VAP, 0.06, 199.3)\n",
    "    \n",
    "#     save_file = f'/home/rodrigo7/Apsim_test/MASAGRO/PCSE/{site}_adv000f.csv'\n",
    "#     with open(save_file, 'w') as sf:\n",
    "#         with open(wfile) as f:\n",
    "#             for r in range(14):\n",
    "#                 sf.writelines(f.readline())\n",
    "    \n",
    "#     w.DAY = w.DAY.astype('str')\n",
    "#     w.to_csv(save_file, na_rep = 'NaN', mode = 'a', float_format = '%.3f', header = False, index = False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e56cd77e35414be183673a5293a13656",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(FloatProgress(value=0.0, max=4594.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 167, in doRollover\n",
      "    os.rename(sfn, dfn)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.6' -> '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "Call stack:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-20'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "--- Logging error ---\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "--- Logging error ---\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 167, in doRollover\n",
      "    os.rename(sfn, dfn)\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 166, in doRollover\n",
      "    os.remove(dfn)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 166, in doRollover\n",
      "    os.remove(dfn)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.6' -> '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "Call stack:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 167, in doRollover\n",
      "    os.rename(sfn, dfn)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 167, in doRollover\n",
      "    os.rename(sfn, dfn)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "Traceback (most recent call last):\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.6' -> '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "Traceback (most recent call last):\n",
      "Call stack:\n",
      "Call stack:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.3' -> '/home/rodrigo7/.pcse/logs/pcse.log.4'\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "Call stack:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 166, in doRollover\n",
      "    os.remove(dfn)\n",
      "Call stack:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "Call stack:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/logging/handlers.py\", line 167, in doRollover\n",
      "    os.rename(sfn, dfn)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "FileNotFoundError: [Errno 2] No such file or directory: '/home/rodrigo7/.pcse/logs/pcse.log.6' -> '/home/rodrigo7/.pcse/logs/pcse.log.7'\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "Call stack:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/traitlets/config/application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelapp.py\", line 583, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/platform/asyncio.py\", line 148, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 538, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/base_events.py\", line 1782, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 787, in inner\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 748, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 361, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/kernelbase.py\", line 541, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/tornado/gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/ipkernel.py\", line 300, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/ipykernel/zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2858, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2886, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3063, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3254, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"<ipython-input-12-739ca1795a84>\", line 4, in <module>\n",
      "    with Pool(processes=30) as p:\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n",
      "    context=self.get_context())\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n",
      "    self._repopulate_pool()\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-20'\n",
      "Arguments: ()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n",
      "    w.start()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 112, in start\n",
      "    self._popen = self._Popen(self)\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n",
      "    return Popen(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-15'\n",
      "Arguments: ()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n",
      "    self._launch(process_obj)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n",
      "    code = process_obj._bootstrap()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-25'\n",
      "Arguments: ()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n",
      "    result = (True, func(*args, **kwds))\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n",
      "  File \"<ipython-input-11-84ad0c4f1a88>\", line 21, in run\n",
      "    wofsim.run_till_terminate()\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 228, in run_till_terminate\n",
      "    self._run()\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-22'\n",
      "Arguments: ()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/engine.py\", line 208, in _run\n",
      "    self.agromanager(self.day, self.drv)\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-07-07'\n",
      "Arguments: ()\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 916, in __call__\n",
      "    self.crop_calendars[0](day)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "  File \"/opt/anaconda3/envs/GEOANN/lib/python3.7/site-packages/pcse/agromanager.py\", line 163, in __call__\n",
      "    self.logger.info(msg)\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-25'\n",
      "Arguments: ()\n",
      "Message: 'Starting crop (maize) with variety (Maize_VanHeemst_1988) on day 2012-06-02'\n",
      "Arguments: ()\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "sites = pts.index.values\n",
    "output = []\n",
    "if __name__ == '__main__':\n",
    "    with Pool(processes=30) as p:\n",
    "        with tqdm(total=len(pts)) as pbar:\n",
    "            for i, df in enumerate(p.imap_unordered(run, sites)):\n",
    "                output.append(df)\n",
    "                pbar.update()\n",
    "\n",
    "output_df = pd.DataFrame([o.iloc[-1] for o in output])\n",
    "output_df.to_hdf('../data/PSCE_npadv010.h5', key = 'SIM')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:GEOANN]",
   "language": "python",
   "name": "conda-env-GEOANN-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
